using SalaamStreet.Desktop.Models;

namespace SalaamStreet.Desktop.Models;

/// <summary>The 114 surahs (self-hosted metadata; total 6236 ayahs).</summary>
public static class Surahs
{
    public static readonly SurahInfo[] All =
    {
        new(1,"الفاتحة","Al-Fatihah","The Opener",7,true),
        new(2,"البقرة","Al-Baqarah","The Cow",286,false),
        new(3,"آل عمران","Aal Imran","Family of Imran",200,false),
        new(4,"النساء","An-Nisa","The Women",176,false),
        new(5,"المائدة","Al-Ma'idah","The Table Spread",120,false),
        new(6,"الأنعام","Al-An'am","The Cattle",165,true),
        new(7,"الأعراف","Al-A'raf","The Heights",206,true),
        new(8,"الأنفال","Al-Anfal","The Spoils of War",75,false),
        new(9,"التوبة","At-Tawbah","The Repentance",129,false),
        new(10,"يونس","Yunus","Jonah",109,true),
        new(11,"هود","Hud","Hud",123,true),
        new(12,"يوسف","Yusuf","Joseph",111,true),
        new(13,"الرعد","Ar-Ra'd","The Thunder",43,false),
        new(14,"إبراهيم","Ibrahim","Abraham",52,true),
        new(15,"الحجر","Al-Hijr","The Rocky Tract",99,true),
        new(16,"النحل","An-Nahl","The Bee",128,true),
        new(17,"الإسراء","Al-Isra","The Night Journey",111,true),
        new(18,"الكهف","Al-Kahf","The Cave",110,true),
        new(19,"مريم","Maryam","Mary",98,true),
        new(20,"طه","Taha","Ta-Ha",135,true),
        new(21,"الأنبياء","Al-Anbya","The Prophets",112,true),
        new(22,"الحج","Al-Hajj","The Pilgrimage",78,false),
        new(23,"المؤمنون","Al-Mu'minun","The Believers",118,true),
        new(24,"النور","An-Nur","The Light",64,false),
        new(25,"الفرقان","Al-Furqan","The Criterion",77,true),
        new(26,"الشعراء","Ash-Shu'ara","The Poets",227,true),
        new(27,"النمل","An-Naml","The Ant",93,true),
        new(28,"القصص","Al-Qasas","The Stories",88,true),
        new(29,"العنكبوت","Al-Ankabut","The Spider",69,true),
        new(30,"الروم","Ar-Rum","The Romans",60,true),
        new(31,"لقمان","Luqman","Luqman",34,true),
        new(32,"السجدة","As-Sajdah","The Prostration",30,true),
        new(33,"الأحزاب","Al-Ahzab","The Combined Forces",73,false),
        new(34,"سبأ","Saba","Sheba",54,true),
        new(35,"فاطر","Fatir","Originator",45,true),
        new(36,"يس","Ya-Sin","Ya Sin",83,true),
        new(37,"الصافات","As-Saffat","Those Who Set the Ranks",182,true),
        new(38,"ص","Sad","The Letter Sad",88,true),
        new(39,"الزمر","Az-Zumar","The Troops",75,true),
        new(40,"غافر","Ghafir","The Forgiver",85,true),
        new(41,"فصلت","Fussilat","Explained in Detail",54,true),
        new(42,"الشورى","Ash-Shuraa","The Consultation",53,true),
        new(43,"الزخرف","Az-Zukhruf","The Ornaments of Gold",89,true),
        new(44,"الدخان","Ad-Dukhan","The Smoke",59,true),
        new(45,"الجاثية","Al-Jathiyah","The Crouching",37,true),
        new(46,"الأحقاف","Al-Ahqaf","The Wind-Curved Sandhills",35,true),
        new(47,"محمد","Muhammad","Muhammad",38,false),
        new(48,"الفتح","Al-Fath","The Victory",29,false),
        new(49,"الحجرات","Al-Hujurat","The Rooms",18,false),
        new(50,"ق","Qaf","The Letter Qaf",45,true),
        new(51,"الذاريات","Adh-Dhariyat","The Winnowing Winds",60,true),
        new(52,"الطور","At-Tur","The Mount",49,true),
        new(53,"النجم","An-Najm","The Star",62,true),
        new(54,"القمر","Al-Qamar","The Moon",55,true),
        new(55,"الرحمن","Ar-Rahman","The Beneficent",78,false),
        new(56,"الواقعة","Al-Waqi'ah","The Inevitable",96,true),
        new(57,"الحديد","Al-Hadid","The Iron",29,false),
        new(58,"المجادلة","Al-Mujadila","The Pleading Woman",22,false),
        new(59,"الحشر","Al-Hashr","The Exile",24,false),
        new(60,"الممتحنة","Al-Mumtahanah","She That Is To Be Examined",13,false),
        new(61,"الصف","As-Saf","The Ranks",14,false),
        new(62,"الجمعة","Al-Jumu'ah","Friday",11,false),
        new(63,"المنافقون","Al-Munafiqun","The Hypocrites",11,false),
        new(64,"التغابن","At-Taghabun","The Mutual Disillusion",18,false),
        new(65,"الطلاق","At-Talaq","The Divorce",12,false),
        new(66,"التحريم","At-Tahrim","The Prohibition",12,false),
        new(67,"الملك","Al-Mulk","The Sovereignty",30,true),
        new(68,"القلم","Al-Qalam","The Pen",52,true),
        new(69,"الحاقة","Al-Haqqah","The Reality",52,true),
        new(70,"المعارج","Al-Ma'arij","The Ascending Stairways",44,true),
        new(71,"نوح","Nuh","Noah",28,true),
        new(72,"الجن","Al-Jinn","The Jinn",28,true),
        new(73,"المزمل","Al-Muzzammil","The Enshrouded One",20,true),
        new(74,"المدثر","Al-Muddaththir","The Cloaked One",56,true),
        new(75,"القيامة","Al-Qiyamah","The Resurrection",40,true),
        new(76,"الإنسان","Al-Insan","The Man",31,false),
        new(77,"المرسلات","Al-Mursalat","The Emissaries",50,true),
        new(78,"النبأ","An-Naba","The Tidings",40,true),
        new(79,"النازعات","An-Nazi'at","Those Who Drag Forth",46,true),
        new(80,"عبس","Abasa","He Frowned",42,true),
        new(81,"التكوير","At-Takwir","The Overthrowing",29,true),
        new(82,"الإنفطار","Al-Infitar","The Cleaving",19,true),
        new(83,"المطففين","Al-Mutaffifin","The Defrauding",36,true),
        new(84,"الإنشقاق","Al-Inshiqaq","The Sundering",25,true),
        new(85,"البروج","Al-Buruj","The Mansions of the Stars",22,true),
        new(86,"الطارق","At-Tariq","The Nightcomer",17,true),
        new(87,"الأعلى","Al-A'la","The Most High",19,true),
        new(88,"الغاشية","Al-Ghashiyah","The Overwhelming",26,true),
        new(89,"الفجر","Al-Fajr","The Dawn",30,true),
        new(90,"البلد","Al-Balad","The City",20,true),
        new(91,"الشمس","Ash-Shams","The Sun",15,true),
        new(92,"الليل","Al-Layl","The Night",21,true),
        new(93,"الضحى","Ad-Duhaa","The Morning Hours",11,true),
        new(94,"الشرح","Ash-Sharh","The Relief",8,true),
        new(95,"التين","At-Tin","The Fig",8,true),
        new(96,"العلق","Al-Alaq","The Clot",19,true),
        new(97,"القدر","Al-Qadr","The Power",5,true),
        new(98,"البينة","Al-Bayyinah","The Clear Proof",8,false),
        new(99,"الزلزلة","Az-Zalzalah","The Earthquake",8,false),
        new(100,"العاديات","Al-Adiyat","The Courser",11,true),
        new(101,"القارعة","Al-Qari'ah","The Calamity",11,true),
        new(102,"التكاثر","At-Takathur","The Rivalry",8,true),
        new(103,"العصر","Al-Asr","The Declining Day",3,true),
        new(104,"الهمزة","Al-Humazah","The Traducer",9,true),
        new(105,"الفيل","Al-Fil","The Elephant",5,true),
        new(106,"قريش","Quraysh","Quraysh",4,true),
        new(107,"الماعون","Al-Ma'un","The Small Kindnesses",7,true),
        new(108,"الكوثر","Al-Kawthar","The Abundance",3,true),
        new(109,"الكافرون","Al-Kafirun","The Disbelievers",6,true),
        new(110,"النصر","An-Nasr","The Divine Support",3,false),
        new(111,"المسد","Al-Masad","The Palm Fiber",5,true),
        new(112,"الإخلاص","Al-Ikhlas","The Sincerity",4,true),
        new(113,"الفلق","Al-Falaq","The Daybreak",5,true),
        new(114,"الناس","An-Nas","Mankind",6,true),
    };
}
